homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 0
  longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
#  - platform: yr

# Tasmota D1mini mqtt sensor
  - platform: mqtt
    name: "Temperature"
    state_topic: "tele/D1mini01/SENSOR"
    value_template: "{{ value_json.DHT11.Temperature }}"
    unit_of_measurement: "C"

  - platform: mqtt
    name: "Humidity"
    state_topic: "tele/D1mini01/SENSOR"
    value_template: "{{ value_json.DHT11.Humidity }}"
    unit_of_measurement: "%"

  - platform: mqtt
    name: "Brightness"
    state_topic: "tele/D1mini01/SENSOR"
    value_template: "{{ value_json.BH1750.Illuminance }}"

  - platform: mitemp_bt
    mac: '4C:65:A8:D7:66:79'
    name: BT Temp
    force_update: false
    median: 1
    monitored_conditions:
      - temperature
      - humidity
      - battery

#  - platform: bme280
#    name: BME280 sensor

  - platform: bh1750


# Text to speech
tts:
  - platform: google

# Cloud
# cloud:


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

mqtt:
  broker: core-mosquitto
  username: urop
  password: urop

switch:
  - platform: mqtt
    name: "Sonoff Switch 02"
    command_topic: "cmnd/sonoffbasic02/power"
    state_topic: "stat/sonoffbasic02/POWER"
    availability_topic: "tele/sonoffbasic02/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

  - platform: mqtt
    name: "Sonoff RF 01"
    command_topic: "cmnd/sonoffrf01/power"
    state_topic: "stat/sonoffrf01/POWER"
    availability_topic: "tele/sonoffrf01/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

  - platform: mqtt
    name: "Sonoff SV"
    command_topic: "cmnd/sonoffsv/power"
    state_topic: "stat/sonoffsv/POWER"
    availability_topic: "tele/sonoffsv/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

  - platform: mqtt
    name: RF Switch
    state_topic: "home/OpenMQTTGateway/433toMQTT"
    command_topic: "home/OpenMQTTGateway/commands/MQTTto433/PLSL_180/433_1"
    payload_on: "5393"
    payload_off: "5396"
#    payload_available: "Online"
#    payload_not_available: "Offline"
    retain: true


#######################################
############## Holiday Outside Lights ######
#######################################

light:
  - platform: mqtt
    name: "Holiday Lights"
    command_topic: "bruh/mqttstrip/setpower"
    state_topic: "bruh/mqttstrip/setpowerpub"
    rgb_state_topic: "bruh/mqttstrip/setcolorpub"
    rgb_command_topic: "bruh/mqttstrip/setcolor"
    brightness_state_topic: "bruh/mqttstrip/setbrightnesspub"
    brightness_command_topic: "bruh/mqttstrip/setbrightness"
    optimistic: false

  - platform: mqtt
    name: "Ben's Holiday Lights"
    command_topic: "bruh/mqttstrip2/setpower"
    state_topic: "bruh/mqttstrip2/setpowerpub"
    rgb_state_topic: "bruh/mqttstrip2/setcolorpub"
    rgb_command_topic: "bruh/mqttstrip2/setcolor"
    brightness_state_topic: "bruh/mqttstrip2/setbrightnesspub"
    brightness_command_topic: "bruh/mqttstrip2/setbrightness"
    optimistic: false

## AiLight ##
  - platform: mqtt
    name: 'Living room lamp'
    state_topic: "stat/arilux01/POWER"
    command_topic: "cmnd/arilux01/POWER"
    rgb_state_topic: "stat/arilux01/COLOR"
    rgb_command_topic: "cmnd/arilux01/COLOR"
    rgb_command_template: "{{ '%02x%02x%02x0000' | format(red, green, blue) }}"
    brightness_state_topic: "stat/arilux01/DIMMER"
    brightness_value_template: "{{ value_json.brightness }}"
    brightness_command_topic: "cmnd/arilux01/DIMMER"
    brightness_scale: 100
#    color_temp_command_topic: "cmnd/arilux01/CT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
#####

input_select:
  holiday_led_effect:
    name: Holiday LED Effect
    options:
     - "Christmas"
     - "Candy Cane"
     - "Holly Jolly"
     - "Valentine"
     - "Lovey Day"
     - "St Patty"
     - "Easter"
     - "USA"
     - "Independence"
     - "Go Blue"
     - "Hail"
     - "Touchdown"
     - "Halloween"
     - "Punkin"
     - "Thanksgiving"
     - "Turkey Day"
     - "BPM"
     - "Confetti"
     - "Cyclon Rainbow"
     - "Dots"
     - "Fire"
     - "Glitter"
     - "Juggle"
     - "Lightning"
     - "Police All"
     - "Police One"
     - "Rainbow"
     - "Rainbow with Glitter"
     - "Ripple"
     - "Sinelon"
     - "Solid"
     - "Twinkle"
    initial: "Solid"


  holiday_led_effect2:
    name: Holiday LED Effect
    options:
     - "Christmas"
     - "Candy Cane"
     - "Holly Jolly"
     - "Valentine"
     - "Lovey Day"
     - "St Patty"
     - "Easter"
     - "USA"
     - "Independence"
     - "Go Blue"
     - "Hail"
     - "Touchdown"
     - "Halloween"
     - "Punkin"
     - "Thanksgiving"
     - "Turkey Day"
     - "BPM"
     - "Confetti"
     - "Cyclon Rainbow"
     - "Dots"
     - "Fire"
     - "Glitter"
     - "Juggle"
     - "Lightning"
     - "Police All"
     - "Police One"
     - "Rainbow"
     - "Rainbow with Glitter"
     - "Ripple"
     - "Sinelon"
     - "Solid"
     - "Twinkle"
    initial: "Solid"

  holiday_led_effect_all:
    name: Holiday LED Effect
    options:
     - "Christmas"
     - "Candy Cane"
     - "Holly Jolly"
     - "Valentine"
     - "Lovey Day"
     - "St Patty"
     - "Easter"
     - "USA"
     - "Independence"
     - "Go Blue"
     - "Hail"
     - "Touchdown"
     - "Halloween"
     - "Punkin"
     - "Thanksgiving"
     - "Turkey Day"
     - "BPM"
     - "Confetti"
     - "Cyclon Rainbow"
     - "Dots"
     - "Fire"
     - "Glitter"
     - "Juggle"
     - "Lightning"
     - "Police All"
     - "Police One"
     - "Rainbow"
     - "Rainbow with Glitter"
     - "Ripple"
     - "Sinelon"
     - "Solid"
     - "Twinkle"
    initial: "Solid"

input_number:
  animation_speed:
    name: Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

  animation_speed2:
    name: Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

  animation_speed_all:
    name: Animation Speed
    initial: 150
    min: 1
    max: 150
    step: 10

automation old:
  - alias: "Holiday Input Effect"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_select.holiday_led_effect
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/mqttstrip/seteffect"
          payload: '{{ trigger.to_state.state | string }}'

  - alias: "Holiday Input Effect 2"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_select.holiday_led_effect2
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/mqttstrip2/seteffect"
          payload: '{{ trigger.to_state.state | string }}'


  - alias: "Holiday Input Effect All"
    initial_state : True
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_select.holiday_led_effect_all
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/mqttstrip/seteffect"
          payload: '{{ trigger.to_state.state | string }}'
      - service: mqtt.publish
        data_template:
          topic: "bruh/mqttstrip2/seteffect"
          payload: '{{ trigger.to_state.state | string }}'

  - alias: "Animation Speed"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.animation_speed
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/mqttstrip/setanimationspeed"
          payload: '{{ trigger.to_state.state | int }}'


  - alias: "Animation Speed 2"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.animation_speed2
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/mqttstrip2/setanimationspeed"
          payload: '{{ trigger.to_state.state | int }}'


  - alias: "Animation Speed All"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_number.animation_speed_all
    action:
      - service: mqtt.publish
        data_template:
          topic: "bruh/mqttstrip/setanimationspeed"
          payload: '{{ trigger.to_state.state | int }}'

      - service: mqtt.publish
        data_template:
          topic: "bruh/mqttstrip2/setanimationspeed"
          payload: '{{ trigger.to_state.state | int }}'
################################

binary_sensor:
#  - platform: mqtt
#    name: Motion Sensor
#    state_topic: "stat/D1mini01/POWER1"

  - platform: mqtt
    name: Touch Switch
    state_topic: "stat/D1mini01/POWER"

  - platform: rpi_gpio
    ports:
      26: Test Switch
